name: ecommerce_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # carousel_slider: ^4.2.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/a.jpg
    - assets/images/b.jpg
    - assets/images/c.jpg
    - assets/images/d.jpg
    - assets/images/e.jpg
    - assets/images/tshirt.jpg
    - assets/images/images.jpg
    - assets/images/user.png
